#### REbuilding that pytorc Training PIPELINE with NN module

In [1]:
import torch
import torch.nn as nn

In [2]:
class model(nn.Module):

    def __init__(self, num_features):


        # Initialize the parent nn.Module class so this model gets all PyTorch module features (parameters, training, saving, etc.)
        super().__init__()

        # sinngle leyer nuron
        self.linear = nn.Linear(num_features, out_features= 1)
        self.sigmoid = nn.Sigmoid()

    def forward (self, features):
        out = self.linear(features)              # we are doing similer like z = WX + B
        out = self.sigmoid(out)                  # we are dping y = sigmoid(z)
        return out

#### Creating Synthetic Dataset

In [3]:
features = torch.rand(10,5)
features.shape[1]

5

#### Creating Model

In [4]:
model = model(features.shape[1])


# FORWARD PASS

#model.forward(features)    ----> we dont need to do this as NN module recomend to do model(features) directly
model(features)             #-----> as we had 10 rows

tensor([[0.2213],
        [0.2290],
        [0.2169],
        [0.2402],
        [0.2777],
        [0.2631],
        [0.2901],
        [0.2880],
        [0.2619],
        [0.2783]], grad_fn=<SigmoidBackward0>)


**`model(features)`** passes the input to the model. PyTorch automatically calls the `forward()` method internally, so we don't need to write `model.forward(features)` explicitly.

In [5]:
# SHOW MODEL's WEIGHT and BIAS

print(model.linear.bias)
model.linear.weight

Parameter containing:
tensor([-0.4111], requires_grad=True)


Parameter containing:
tensor([[-0.3959, -0.4254, -0.4289, -0.0966, -0.0577]], requires_grad=True)

#### 

5 weights as we had 5 features , 1 bias as we had one 1 output

#### we can visualize whole network by TORCHIFO ---> SuMMARY

In [6]:
# !pip install torchinfo

!

In [7]:
from torchinfo import summary

summary(model, input_size = (10,5))

ModuleNotFoundError: No module named 'torchinfo'

: 