In [1]:
import torch

a = torch.tensor([[1,2,3], [4,5,6]])
a


tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
a.shape

torch.Size([2, 3])

In [3]:
# Copy shape of any TENSOR
torch.empty_like(a)            #here i am copying x's shape

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 3617910444157646436]])

In [4]:
torch.ones_like(a)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [5]:
# torch.rand_like(a)  
"""
This will give ERROR as, we are copying "A" which contais all INTIGER, but RAND gives 0 to 1 floats
so, there will be DATA TYPE error

so we have to change the data type 
like ---->
"""

torch.rand_like(a, dtype=torch.float64)

tensor([[0.1845, 0.7886, 0.4018],
        [0.3920, 0.7088, 0.9236]], dtype=torch.float64)