In [28]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [29]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:, 0])

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

label = LabelEncoder()
y_train = label.fit_transform(y_train)
y_test = label.transform(y_test)

print(y_test)


[0 0 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0 1 0 1 0 0 1 1 0 1 0 0 0 1 0 0 1 0 1 0 0
 0 0 1 1 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 1 1 1 0 1 0 1 0 0
 0 0 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 1 1 1 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0
 1 1 1 1 1 0 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 1 1 0 0 0 1]


In [30]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [31]:
bias = torch.rand(1, dtype=torch.float64, requires_grad= True)

X_train_tensor = X_train_tensor.to(torch.float32)
X_train_tensor = X_train_tensor.float()
y_train_tensor = y_train_tensor.float()

## Dataloaders and Dataset

In [32]:
from torch.utils.data import Dataset, DataLoader

In [33]:
class CustomDataloader(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [34]:
train_dataset = CustomDataloader(X_train_tensor, y_train_tensor)
test_dataset = CustomDataloader(y_train_tensor, y_test_tensor)

In [35]:
train_dataset[:]

(tensor([[-0.8463,  0.7156, -0.8381,  ..., -0.7687,  0.3910, -0.2292],
         [ 2.0574,  0.6789,  2.0839,  ...,  1.8918,  1.4364,  0.8802],
         [ 2.5838,  1.1342,  2.5128,  ...,  1.3943, -0.5227, -0.3892],
         ...,
         [ 0.9464,  0.9192,  1.0660,  ...,  1.2553, -0.9859,  2.0613],
         [ 0.2149, -0.0485,  0.1855,  ...,  0.4978,  0.0626,  0.0103],
         [-0.1148, -1.3822, -0.1740,  ..., -0.8600, -0.1579, -0.9030]]),
 tensor([0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 0., 1., 0.,
         0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1.,
         1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
         0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1.,
         0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
         1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,

In [36]:
train_dataset[10]

(tensor([-0.4888, -0.9773, -0.5528, -0.5096, -1.2343, -1.3391, -0.9905, -0.9660,
         -1.0086, -0.7650, -1.0305, -0.9832, -1.0163, -0.6659, -1.2113, -1.2011,
         -0.9472, -1.3269, -0.4130, -1.0378, -0.6435, -0.8564, -0.7028, -0.6020,
         -1.2625, -1.1336, -1.0132, -1.1215, -0.0341, -0.9090]),
 tensor(0.))

In [37]:
test_dataset[10]

(tensor(0.), tensor(0))

In [38]:
train_dataloader = DataLoader(train_dataset, batch_size=32, shuffle= True)
test_dataloader = DataLoader(test_dataset, batch_size=32, shuffle= True)

## Defining Model

In [39]:
class simpleNN(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        pass
        self.model = nn.Sequential(
            nn.Linear(num_features,1),
            nn.Sigmoid()
        )

    def forward(self, features):    
        return self.model(features)

In [40]:
model = simpleNN(X_test_tensor.shape[1])   # number of input features/ Columns

learning_rate = 0.1
epochs = 45


optimizer = torch.optim.SGD(model.parameters(), lr= learning_rate)

loss_func = nn.BCELoss()

In [41]:
for name, param in model.named_parameters():
    print(name, param.shape)

model.0.weight torch.Size([1, 30])
model.0.bias torch.Size([1])


In [42]:
for epoch in range(epochs):

    for batch_features, batch_labels in train_dataloader:

        #FORWARD PASS
        y_pred = model(batch_features)

        #loss
        loss = loss_func(y_pred, batch_labels.view(-1,1))

        #  Zero grads
        optimizer.zero_grad()

        # Backward pass
        loss.backward()

        # Updating Gradients's parameters
        optimizer.step()


        print (f"{epoch} and loss {loss.item()}")

0 and loss 1.29050874710083
0 and loss 0.8113039135932922
0 and loss 0.5505686402320862
0 and loss 0.5562383532524109
0 and loss 0.33139926195144653
0 and loss 0.3630625307559967
0 and loss 0.37311848998069763
0 and loss 0.36577582359313965
0 and loss 0.3497900664806366
0 and loss 0.3339551091194153
0 and loss 0.25750869512557983
0 and loss 0.3652532696723938
0 and loss 0.28199172019958496
0 and loss 0.2733660042285919
1 and loss 0.19739285111427307
1 and loss 0.35058873891830444
1 and loss 0.15755842626094818
1 and loss 0.2161545306444168
1 and loss 0.15728098154067993
1 and loss 0.27136215567588806
1 and loss 0.16198816895484924
1 and loss 0.19979821145534515
1 and loss 0.17214660346508026
1 and loss 0.21285231411457062
1 and loss 0.1442512571811676
1 and loss 0.15993010997772217
1 and loss 0.11368609219789505
1 and loss 0.21635957062244415
2 and loss 0.19622907042503357
2 and loss 0.17596162855625153
2 and loss 0.17183135449886322
2 and loss 0.09390369057655334
2 and loss 0.10294201

In [43]:
# Model Evaluation

y_pred = y_pred.float()
with torch.no_grad():                     # Disable gradient calculation

    y_pred = model(X_test_tensor.float()) # Predict probabilities

    y_pred = (y_pred > 0.5).float()       # Convert probabilities to 0 or 1

    accuracy = (y_pred == y_test_tensor).float().mean()  # Calculate accuracy

    print(f"Accuracy: {accuracy.item()}") # Print accuracy

Accuracy: 0.5471172332763672
