#### Our Goal is to make a Basics understanding of AutoGrad
##### we will create tenosors, do Forward propagrations and then Back Prop

In [145]:
import torch

In [146]:
x = torch.tensor([3.0], requires_grad= True)
x


tensor([3.], requires_grad=True)

#### Forward Prop
will do the relations ship of the variable // in simle lang will make the equations of the Componets of which we want Gradient,,,,,,

we want the gradient of (x^2 + 3) for value of x = 3

In [147]:
y = x**2
z = y + 3

In [148]:
y, z

(tensor([9.], grad_fn=<PowBackward0>), tensor([12.], grad_fn=<AddBackward0>))

##### Back Prop starting

In [149]:
z.backward()

In [150]:
x.grad

tensor([6.])

### AFTER EVERY Gradient We have to Clear the GRAD

In [151]:
x.grad.zero_()
x.requires_grad_(False)

tensor([3.])

In [152]:
y

tensor([9.], grad_fn=<PowBackward0>)

### Find GRADIENT For Sin(x^2)

In [153]:
x = torch.tensor([4.0], requires_grad= True)

y = x**2
z = torch.sin(y)
y,z

(tensor([16.], grad_fn=<PowBackward0>),
 tensor([-0.2879], grad_fn=<SinBackward0>))

In [154]:
z.backward()


In [155]:
x,y,z

(tensor([4.], requires_grad=True),
 tensor([16.], grad_fn=<PowBackward0>),
 tensor([-0.2879], grad_fn=<SinBackward0>))

In [156]:
x.grad



tensor([-7.6613])

In [157]:
x.grad.zero_()
x.requires_grad_(False)

tensor([4.])

### QUEST 1, Simple NN

In [158]:
# Question:
# Implement Logistic Regression for a single training example using PyTorch tensors.
#
# Given:
# x = 8.11  (CGPA)
# y = 1     (Placed)
#
# Initialize:
# w = 0.5
# b = -3.0
#
# Tasks:
# 1. Compute the linear transformation:
#       z = w*x + b
#
# 2. Apply the sigmoid activation:
#       y_hat = 1 / (1 + exp(-z))
#
# 3. Compute the Binary Cross Entropy Loss:
#       L = -(y*log(y_hat) + (1-y)*log(1-y_hat))
#
# 4. Enable gradient tracking for w and b.
#
# 5. Perform backpropagation using:
#       loss.backward()
#
# 6. Print:
#       z
#       y_hat
#       loss
#       w.grad
#       b.grad
#
# 7. Update the parameters using Gradient Descent:
#       w = w - lr*w.grad
#       b = b - lr*b.grad
#
# Use learning rate:
#       lr = 0.01

In [159]:
x = torch.tensor([6.13])
y = torch.tensor([0])

In [160]:
w = torch.tensor(1.0, requires_grad= True)
b = torch.tensor(0.0, requires_grad= True)
w,b

(tensor(1., requires_grad=True), tensor(0., requires_grad=True))

In [161]:
z = w*x + b
y_pred = torch.sigmoid(z)
z, y_pred

(tensor([6.1300], grad_fn=<AddBackward0>),
 tensor([0.9978], grad_fn=<SigmoidBackward0>))

In [162]:
def binary_cross_entropy_loss(c,d):
    L = -(d*torch.log(c) + (1-d)*torch.log(1-c))
    return L

loss = binary_cross_entropy_loss(y_pred, y)

loss

tensor([6.1322], grad_fn=<NegBackward0>)

In [163]:
loss.backward()

In [164]:
w.grad, b.grad

(tensor(6.1167), tensor(0.9978))

#### Gradient of [(x1^2+x2^2+x3^2)/3], for x = 1,2,3

In [165]:
x = torch.tensor([1,2,3], requires_grad= True, dtype=torch.float32)
y = (x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [166]:
y.backward()

In [167]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [168]:
x.grad.zero_()

tensor([0., 0., 0.])

In [169]:
x.grad

tensor([0., 0., 0.])