In [3]:
import torch

a = torch.rand(2,3)
b = torch.rand(2,3)

In [4]:
print(a)
print(b)

tensor([[0.4466, 0.5788, 0.0087],
        [0.0398, 0.3290, 0.0674]])
tensor([[0.2259, 0.6534, 0.3769],
        [0.2405, 0.5069, 0.3288]])


In [5]:
a+2

tensor([[2.4466, 2.5788, 2.0087],
        [2.0398, 2.3290, 2.0674]])

In [6]:
a-b

tensor([[ 0.2207, -0.0746, -0.3682],
        [-0.2007, -0.1779, -0.2614]])

In [11]:
abs(a-b)

tensor([[0.2207, 0.0746, 0.3682],
        [0.2007, 0.1779, 0.2614]])

In [7]:
a*b

tensor([[0.1009, 0.3782, 0.0033],
        [0.0096, 0.1667, 0.0221]])

In [8]:
a//b

tensor([[1., 0., 0.],
        [0., 0., 0.]])

In [9]:
a%b


tensor([[0.2207, 0.5788, 0.0087],
        [0.0398, 0.3290, 0.0674]])

In [14]:
c=torch.abs(a**b)

In [15]:
torch.neg(c)

tensor([[-0.8335, -0.6996, -0.1675],
        [-0.4606, -0.5692, -0.4119]])

In [16]:
torch.round(c)

tensor([[1., 1., 0.],
        [0., 1., 0.]])

In [19]:
d = torch.tensor([1.9,2.4,3.1,4, 4.1])

In [20]:
torch.ceil(d)

tensor([2., 3., 4., 4., 5.])

In [21]:
torch.floor(d)

tensor([1., 2., 3., 4., 4.])

In [23]:
torch.clamp(d, min = 2, max = 6)

tensor([2.0000, 2.4000, 3.1000, 4.0000, 4.1000])

### REDUCTIONS Operation

In [35]:
e = torch.randint(size = (3,2), low = 1, high = 6)
e

tensor([[5, 2],
        [2, 3],
        [4, 1]])

In [36]:
#sum
torch.sum(e)

tensor(17)

In [ ]:
# sum of columns -->0
torch.sum(e, dim = 0)

tensor([11,  6])

In [38]:
# Sum of ROWs -->1
torch.sum(e, dim =1)

tensor([7, 5, 5])

In [43]:
f = torch.randint(size = (3,2), low = 1, high = 6, dtype= torch.float32)
f


tensor([[1., 1.],
        [1., 2.],
        [5., 2.]])

In [44]:
torch.mean(f)

tensor(2.)

In [45]:
torch.mean(f, dim = 0)

tensor([2.3333, 1.6667])

In [46]:
torch.median(f, dim = 1)

torch.return_types.median(
values=tensor([1., 1., 2.]),
indices=tensor([0, 0, 1]))

similarly we have MAX, MEAN STD, PRODUCT, VAR

In [ ]:
torch.argmax(f)   # Position of max element

tensor(4)

In [48]:
torch.argmin(f)

tensor(0)