In [1]:
import torch


In [2]:
a = torch.tensor([1,2,3])
b = a

a,b

(tensor([1, 2, 3]), tensor([1, 2, 3]))

a and b point to the same memory location.
They are not two separate tensors.

Therefore, if we change a,
b will also change automatically.


example-->

In [3]:
a[1] = 99
a


tensor([ 1, 99,  3])

In [4]:
b

tensor([ 1, 99,  3])

#### To create an independent copy, use clone().

In [5]:
v = torch.tensor([1,2,3])
v


tensor([1, 2, 3])

In [6]:
g = v.clone()
g

tensor([1, 2, 3])

In [7]:
v[1] = 99
v

tensor([ 1, 99,  3])

In [8]:
g

tensor([1, 2, 3])

#### clone() creates a new tensor with its own memory location.
#### Changes in one tensor will not affect the other.