In [1]:
import torch

In [2]:
# Using Empty
torch.empty(2,3)


tensor([[4.4171e+21, 4.4148e+21, 7.2155e+22],
        [7.2250e+28, 1.8666e+25, 1.7863e+25]])

In [4]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
torch.ones(1,4)

tensor([[1., 1., 1., 1.]])

In [ ]:
# RANDOM number's tensor (0 to 1)

torch.rand(2,3)

tensor([[0.0926, 0.8439, 0.1158],
        [0.7418, 0.5498, 0.7152]])

In [14]:
torch.rand(2,3)

tensor([[0.6373, 0.2421, 0.7312],
        [0.7224, 0.1992, 0.6948]])

#### torch.rand will create RANDOM numbers each time
#### to over comethis we can use MANUAL_SEED()
#### this will help us to maintian a same randomized TEnsor for work

In [11]:
torch.manual_seed(12)
# torch.randint(3,2)     ----> this will be ERROR
# as randint wants .randint(starting number, Endingnumber-Excluded, (m,n))

torch.randint(10, 20, (3,2))

tensor([[13, 13],
        [12, 17],
        [13, 16]])

In [ ]:
torch.randint(10, 20, (3,2))

tensor([[13, 13],
        [12, 17],
        [13, 16]])

### 1D Array

In [ ]:
torch.arange(10, 67, 3)

#      (start, end, Step count)

tensor([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61,
        64])

In [ ]:
torch.linspace(10,67, 3)

#     (start, end, total ele of torch)

tensor([10.0000, 38.5000, 67.0000])