In [1]:
import torch

In [2]:
d = torch.randint(size = (3,3), low = 1, high = 13)
e = torch.randint(size = (3,3), low = 1, high = 13)

d,e

(tensor([[ 8,  9, 11],
         [ 4,  3,  1],
         [10, 11,  9]]),
 tensor([[ 4, 10,  3],
         [10,  1, 11],
         [ 6,  1,  5]]))

#### FOr in place operation we just have to use '_'
#### for example--> d.add_(e)           
### veraible.operations_()

In [3]:
d.add(e)

tensor([[12, 19, 14],
        [14,  4, 12],
        [16, 12, 14]])

In [5]:
d

tensor([[ 8,  9, 11],
        [ 4,  3,  1],
        [10, 11,  9]])

In [6]:
d.add_(e)

tensor([[12, 19, 14],
        [14,  4, 12],
        [16, 12, 14]])

In [7]:
d

tensor([[12, 19, 14],
        [14,  4, 12],
        [16, 12, 14]])