In [5]:
import torch

a = torch.randint(size = (2,3), low = 0, high = 10 )
b = torch.randint(size = (3,2), low = 0, high = 10)

a

tensor([[8, 3, 2],
        [9, 9, 9]])

In [6]:
b

tensor([[2, 5],
        [6, 9],
        [4, 2]])

In [7]:
# Matrix Multiplication
torch.matmul(a,b)

tensor([[ 42,  71],
        [108, 144]])

### TRANSPOSE

#### Transpose of 2D

In [28]:
a,b

(tensor([[8, 3, 2],
         [9, 9, 9]]),
 tensor([[2, 5],
         [6, 9],
         [4, 2]]))

In [26]:
# Tranpose

torch.transpose(a, 1,0)

tensor([[8, 9],
        [3, 9],
        [2, 9]])

In [27]:
torch.transpose(a, 0,1)

tensor([[8, 9],
        [3, 9],
        [2, 9]])

In [29]:
torch.transpose(b, 0, 1)

tensor([[2, 6, 4],
        [5, 9, 2]])

#### Transpose of 3D matrix

In [31]:
x = torch.tensor([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

x

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [37]:
"""Dimension 0 (2 blocks)
│
├── Block 0
│   [[1, 2, 3],
│    [4, 5, 6]]
│
└── Block 1
    [[7, 8, 9],
     [10,11,12]]
     
So:
dim 0 = which block (2 blocks)
dim 1 = rows in each block (2 rows)
dim 2 = columns in each row (3 columns)
"""

'Dimension 0 (2 blocks)\n│\n├── Block 0\n│   [[1, 2, 3],\n│    [4, 5, 6]]\n│\n└── Block 1\n    [[7, 8, 9],\n     [10,11,12]]\n     \nSo:\ndim 0 = which block (2 blocks)\ndim 1 = rows in each block (2 rows)\ndim 2 = columns in each row (3 columns)\n'

##### Swaping dim 0 and 2

In [33]:
torch.transpose(x, 0, 2)

tensor([[[ 1,  7],
         [ 4, 10]],

        [[ 2,  8],
         [ 5, 11]],

        [[ 3,  9],
         [ 6, 12]]])

In [34]:
torch.transpose(x, 0, 1)

tensor([[[ 1,  2,  3],
         [ 7,  8,  9]],

        [[ 4,  5,  6],
         [10, 11, 12]]])

#### DOT Products

In [14]:
v1 = torch.tensor([1,2])
v2 = torch.tensor([3,4])

print(v1,"\n",v2)

tensor([1, 2]) 
 tensor([3, 4])


In [15]:
torch.dot(v1, v2)

tensor(11)

#### determinant


In [40]:
c = torch.randint(size = (3,3), low = 0, high = 10, dtype= torch.float32)
c

tensor([[5., 5., 9.],
        [1., 9., 9.],
        [1., 2., 3.]])

In [41]:
torch.det(c)

tensor(12.0000)

In [42]:
# Inverse

torch.inverse(c)

tensor([[ 0.7500,  0.2500, -3.0000],
        [ 0.5000,  0.5000, -3.0000],
        [-0.5833, -0.4167,  3.3333]])

#### COMPARISON

In [46]:
d = torch.randint(size = (3,3), low = 1, high = 13)
e = torch.randint(size = (3,3), low = 1, high = 13)

d,e

(tensor([[ 8, 10,  2],
         [ 9,  1,  2],
         [10,  1,  5]]),
 tensor([[ 1,  2,  1],
         [10,  4, 12],
         [ 6,  6,  4]]))

In [47]:
d>e

tensor([[ True,  True,  True],
        [False, False, False],
        [ True, False,  True]])

In [48]:
d==e

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [49]:
d>=e

tensor([[ True,  True,  True],
        [False, False, False],
        [ True, False,  True]])

In [50]:
d!=e

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

#### Special Operations

In [51]:
torch.log(d)

tensor([[2.0794, 2.3026, 0.6931],
        [2.1972, 0.0000, 0.6931],
        [2.3026, 0.0000, 1.6094]])

In [53]:
torch.sqrt(d)

tensor([[2.8284, 3.1623, 1.4142],
        [3.0000, 1.0000, 1.4142],
        [3.1623, 1.0000, 2.2361]])

In [58]:
torch.exp(e)

tensor([[2.7183e+00, 7.3891e+00, 2.7183e+00],
        [2.2026e+04, 5.4598e+01, 1.6275e+05],
        [4.0343e+02, 4.0343e+02, 5.4598e+01]])

In [59]:
torch.sigmoid(e)

tensor([[0.7311, 0.8808, 0.7311],
        [1.0000, 0.9820, 1.0000],
        [0.9975, 0.9975, 0.9820]])