#### REbuilding that pytorc Training PIPELINE with NN module

In [39]:
import torch
import torch.nn as nn

In [40]:
class model(nn.Module):

    def __init__(self, num_features):


        # Initialize the parent nn.Module class so this model gets all PyTorch module features (parameters, training, saving, etc.)
        super().__init__()

        # sinngle leyer nuron
        self.linear = nn.Linear(num_features, out_features= 1)
        self.sigmoid = nn.Sigmoid()

    def forward (self, features):

        out = self.linear(features)              # we are doing similer like z = WX + B
        out = self.sigmoid(out)                  # we are dping y = sigmoid(z)
        return out

#### Creating Synthetic Dataset

In [41]:
features = torch.rand(10,5)
features.shape[1]

5

#### Creating Model

In [42]:
model = model(features.shape[1])


# FORWARD PASS

#model.forward(features)    ----> we dont need to do this as NN module recomend to do model(features) directly
model(features)             #-----> as we had 10 rows

tensor([[0.6383],
        [0.5613],
        [0.5810],
        [0.6077],
        [0.5616],
        [0.5692],
        [0.6050],
        [0.5743],
        [0.5582],
        [0.5175]], grad_fn=<SigmoidBackward0>)


**`model(features)`** passes the input to the model. PyTorch automatically calls the `forward()` method internally, so we don't need to write `model.forward(features)` explicitly.

In [43]:
# SHOW MODEL's WEIGHT and BIAS

print(model.linear.bias)
model.linear.weight

Parameter containing:
tensor([0.3754], requires_grad=True)


Parameter containing:
tensor([[-0.1368, -0.3332,  0.3536, -0.3094,  0.1393]], requires_grad=True)

#### 

5 weights as we had 5 features , 1 bias as we had one 1 output

#### we can visualize whole network by TORCHIFO ---> SuMMARY

In [46]:
# !pip install torchinfo

!

In [45]:
from torchinfo import summary

summary(model, input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00